# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('A', 'Admin'), ('G', 'Guest')], default='G', max_length=1),
        ),
    ]
