# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('category', models.CharField(choices=[('Fy', 'Funny'), ('Ss', 'Serious'), ('Sx', 'Sexy'), ('Ct', 'Cute'), ('Cm', 'Cameo'), ('Nc', 'Nostalgic')], default='Fy', max_length=2)),
                ('rhetoric', models.CharField(choices=[('E', 'Ethos'), ('P', 'Pathos'), ('L', 'Logos'), ('K', 'Kairos'), ('T', 'Topos')], default='P', max_length=1)),
                ('efficacy', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('industry', models.CharField(choices=[('RL', 'Retail'), ('AT', 'Automotive'), ('TC', 'Telecom'), ('FN', 'Financial'), ('RT', 'Restaurants'), ('IN', 'Insurance'), ('PH', 'Pharmaceutical'), ('FD', 'Food'), ('TR', 'Travel'), ('RM', 'Remedies')], default='RL', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercials.Commercial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.AddField(
            model_name='commercial',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercials.Company'),
        ),
        migrations.AddField(
            model_name='adpost',
            name='commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercials.Commercial'),
        ),
        migrations.AddField(
            model_name='adpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
