# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpost',
            name='content',
            field=models.TextField(default='', max_length=250),
        ),
    ]
