# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0002_adpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='company',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
