# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0003_auto_20170129_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='commercials.Commercial'),
        ),
    ]
