# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0004_auto_20170130_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='youtube',
            field=models.CharField(default='', max_length=100),
        ),
    ]
