# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0005_commercial_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='title',
            field=models.CharField(default='', max_length=45),
        ),
    ]
